config/routes.rb
Rails.application.routes.draw do
  
resources :users do
  resources :posts
end
  get '/' => 'home#index', as: :home # there is no index action in your home controller

end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all #this will show all posts for your app, if you want to only show a users posts...
		# @oosts = Post.where(user_id: @user.id)
		@user = User.where(params[:user_id]).first # this will give you an error if you try to go to /posts, but since you dont have routes for that it is ok
	end

	def show
		@posts = Post.find(params[:id]) #same as above, to scope to the user '/users/1/posts/1'...
		# @user = User.where(params[:user_id]).first
		# @post = @user.posts.find(params[:id]) # note that @post is singular for showing 1 post
	end

	def new
		@post = Post.new # same idea as above
		@user = User.where(params[:user_id]).first
		
		# @post = @user.posts.new # this will creata new post for a specific user if desired (not required)
	end

	def create
		@posts = Post.new(params[:id])

		if @posts.save 
			flash[:notice] = "Post successfully created!"
			redirect_to user_posts_path
		else
			flash[:alert] = "Your post could not be saved"
			redirect_to user_posts_path
		end
	
	
	end
	
	####################
	# missing methods
	def edit
	end
	
	def update
	end
	
	def destroy
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
	  @users = User.all
	  # if @users.present?
	  # flash[:notice] = "Users display successfully."
	  # else
	  # flash[:alert] = "Sorry, there were no users to
	  # display."
	  # end
 	

    end

	def show
    @user = User.find(params[:id])

    end

    def edit
    	@user = User.find(params[:id]) # @user should be singular
    
    end

    def new
    	@user = User.new # @user should be singular
    end
    
    def create
		@user = User.new(params_users) # @user should be singular
		@user.save
		if @user.save
			flash[:notice] = "Your account has been saved successfully!"
			redirect_to users_path
		else 	
			flash[:alert] = "We've experienced a problem, your account could not be saved"
			# redirect_to root_path
		end

		end

		def destroy
		@user = User.find(params[:id])
	
			if @user.destroy
			flash[:notice] = "You've been destroyed!"
			else 
				flash[:alert] = "You must be impervious to deletion"
			end
			redirect_to home_path
		

		end

		 def update
	     @user = User.find(params[:id])
	     if @user.update(params_users)
			flash[:notice] = "User info was updated"
			else 
				flash[:alert] = "You must be impervious to update"
			end
			redirect_to home_path

	    end

		private

		def params_users
		params.require(:user).permit(:fname, :lname, :email, :password)
		end



   
#     end

#     def destroy
# 		@user = User.find(params[:id])  
# 		if @user.destroy    
# 		flash[:notice] = "User account has been removed "  
# 		else    
# 		flash[:alert] = "We can't remove this account for the moment"  
# 		end  
# 		redirect_to users_path
# 	end

    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/about.html.erb
<h1>yo</h1>

app/views/home/index.html.erb
<h1>welcome</h1>

<br>

<%= link_to 'users page', users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restful</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:notice] if flash[:notice] %>
<%= flash[:alert] if flash[:alert] %>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>Posts index page</h1>

<%= @posts.each do |post| %>
  <%= post.subject %>
   <%= post.body %>
    <br>
  <% end %>

  <%# Tried supplying a link to create a new post but rain into some difficulty
  <%= link_to "Create a new post", new_user_post_path(@user) %>  <!-- it needs to know the user -->

app/views/posts/new.html.erb
<h1>Create a post!</h1>

<%= form_for [@user, @post] do |f| %>
 <%=f.label :subject %>
 <%=f.text_field :subject%>
 <%=f.label :body %>
 <%=f.text_field :body%>
 <%=f.submit %>


 <% end %>

app/views/posts/show.html.erb
show.html.erb

app/views/users/edit.html.erb
<h1>Edit your user here</h1>

<%= form_for @users do |f| %>
 <%=f.label :fname %>
 <%=f.text_field :fname%>
 <%=f.label :lname %>
 <%=f.text_field :lname%>
 <%=f.label :email %>
 <%=f.text_field :email %>
 <%=f.label :password %>
 <%=f.text_field :password %>
 <%=f.submit :update %>

 <% end %>

app/views/users/index.html.erb
<h1>Users index page</h1>

<% @users.each do |user| %>
  <%= user.fname %>
  <%= user.lname %>
  <%= user.email %>
  <%= link_to 'edit user', edit_user_path(user) %>
  <%= link_to 'show user', user_path(user) %>
  <%= link_to 'delete user', user_path(user), method: :delete %>
<%= link_to 'new user', new_user_path(user) %>
  <br>

  <% end %>

 

app/views/users/new.html.erb
<h1>New user page</h1>

<%= form_for @users do |f| %>
 <%=f.label :fname %>
 <%=f.text_field :fname%>
 <%=f.label :lname %>
 <%=f.text_field :lname%>
 <%=f.label :email %>
 <%=f.text_field :email %>
 <%=f.label :password %>
 <%=f.text_field :password %>
 <%=f.submit :create %>


  <% end %>

app/views/users/show.html.erb
<%=@user.fname %>
 <%=@user.lname %>
 <%=@user.email %>
 <%=@user.password %>

 <%= link_to "This user's posts", user_posts_path(@user) %>
<%= link_to "New post", new_user_post_path(@user) %>